### ISSUE TITLE
Thumbnail image quality is drastically reduced after latest updates

### ISSUE THREAD

**Issue by erdemyerebasmaz** [amugofjava/anytime_podcast_player#29]
Podcast list items and episode tiles thumbnail image quality is reduced after latest updates.

<img src="https://user-images.githubusercontent.com/4012752/108704354-f121f280-751c-11eb-9b0e-bfd7a23de5ad.jpg"  width="300" /><img src="https://user-images.githubusercontent.com/4012752/108704358-f2ebb600-751c-11eb-9dd9-2b27470bfc42.jpg" width="300" />

**Comment by amugofjava** [comment]
Hi @erdemyerebasmaz,

This only happens when using PodcastIndex as the search provider. The issue here is that the iTunes API includes pre-scaled thumbnail images within its search results; PodcastIndex search returns links to the podcasts, but does not itself provide thumbnail images. The the only option we have is to use the full-size artwork image provided in the podcast RSS. These are high-resolution images which then need to be scaled down to 60w and cached in order to be displayed as a thumbnail image. Whilst it is possible to use the full size image as a thumbnail the additional processing and RAM overhead results in a significant drop in performance and frequent crashes as the GC cannot free enough memory to accommodate the images.

I am investigating options to get around this including recent updates to the Flutter cache manager.

**Comment by amugofjava** [comment]
I have set some of the images to a fixed size. This should improve the thumbnail quality and also prevent flickering on the hero image where the cached image manager was attempting to process different sized images for every frame. Still work in progress, but hopefully this is at least improved.

**Comment by erdemyerebasmaz** [comment]
It definitely is less pixelated and readability is on acceptable levels now, thank you 🙏
