### ISSUE TITLE
Ability to modify search or add RSS feeds

### ISSUE THREAD

**Issue by OptimalHRV** [amugofjava/anytime_podcast_player#3]
I am hoping the tittle gives you an idea of what might be super useful. 
Any chance of modifying the search or adding a new URL for the feed?

The results are always the same and so wondered if I am missing something. I am not able to find, where you are getting this list in the discover tab. Is there an option to include curated list?

**Comment by amugofjava** [comment]
The discovery tab pulls in the top 20 podcasts as reported by iTunes. As the data doesn't change that frequently the results are cached in the app to avoid unnecessary network calls; however they are currently cached for as long as the app is running which is why the results don't change once fetched. I will be adding a time limit on the cache and pull-to-refresh so you can manually force a refresh. I will also be adding categories to the discovery tab so you can find podcasts by genre.

I will also be adding support for manually adding a podcast RSS feed.

I built a separate library to handle the searching and discovery features called [podcast_search](https://github.com/amugofjava/podcast_search) which you can take a look at if you want to see how where the data comes from.

**Comment by OptimalHRV** [comment]
Ah, I see. I went to the https://rss.itunes.apple.com/en-gb
Using the filters, I got this link: https://rss.itunes.apple.com/api/v1/gb/podcasts/top-podcasts/all/10/explicit.json

Makes so much sense. However, the manual RSS feed would be absolute golden.

**Comment by amugofjava** [comment]
Yes, I agree. No matter which podcast search index you use there will always be some podcasts that don't appear and need adding manually, so that feature will definitely be coming.
