### ISSUE TITLE
Empty player after existing the app using Android back button

### ISSUE THREAD

**Issue by kingonly** [amugofjava/anytime_podcast_player#6]
Player is blank after existing the app using the device's back button.

**To Reproduce**
1. Play any podcast episode.
2. Close the podcast view and go back to the Library view.
3. Click on Android back button.
4. Notice the player is empty. It's also empty in full screen mode.

**Expected behavior**
Player shows the episode details.

**Video**
https://drive.google.com/file/d/1UB_prI9P7mjHC0x-KFEFrVxuLD0Zj0hN/view?usp=drivesdk

**Smartphone:**
 - Device: OnePlus 6
 - OS: Android 10

**Additional context**
Regression from the latest update it seems.

**Comment by amugofjava** [comment]
Thanks @kingonly for raising this issue and for the video - it made it very easy to track down the bug.

The issue here is that tapping the back button from the library takes you back to the OS at which point Anytime is destroyed, leaving just the audio to play in the background. When returning to Anytime it can detect playback is in progress, but the podcast and episode states have been lost resulting in the blank mini player and details screen.

The solution is to correctly persist current podcast and episode state when the OS suspends the app and restore it on resume. I will start work on this fix as soon as I can.

**Comment by kingonly** [comment]
Wonderful, love the new features btw 🙏💪

**Comment by mohammad-soltani77** [comment]
Hi 
do still this bug exist ?

**Comment by amugofjava** [comment]
Yes, this is still an open bug. Currently work in progress.

**Comment by kingonly** [comment]
I still see the bug (in the Breez integration). Can you point us to the fix to make it's included in our build?

**Comment by amugofjava** [comment]
In `mobile_audio_player_service`, the resume method now returns an `Episode`. The mini player is then populated with this episode if non-null. I do still have some work to do on preserving state, but this does appear to be improved.

**Comment by kingonly** [comment]
Indeed the issue is specific to the Breez integration. We'll take a look. Thank you so much.
