### ISSUE TITLE
Accept HTTP connection ?

### ISSUE THREAD

**Issue by Chralu** [amugofjava/anytime_podcast_player#62]
**Is your feature request related to a problem? Please describe.**
Some RSS provide `http` URLs  (without SSL)  to download audio files.

In that case, clicking on the episode download button does nothing (on iOS).
Whereas stream reading episodes works perfectly.

**Describe the solution you'd like**
As audio file downloading is not risked, maybe we should accept `HTTP` connections.

**Comment by amugofjava** [comment]
Hi @Chralu,

Do you have a couple of example podcasts or URLs I can try to reproduce this?

Thanks.

**Comment by amugofjava** [comment]
Those two values were set as part of the setup of the `just_audio` plugin; however, looking at the docs you have posted I read that as `NSAllowsArbitraryLoadsForMedia` disables `NSAllowsArbitraryLoads`. I will do some testing with the two flags.

**Comment by Chralu** [comment]
Hi,
this issue is problematic for my daily use of anytime podcast.

I made a PR to enforce systematic https usage.
If that solution doesn't suit the project, I can make another PR to accept non-http connections on iOS.

@amugofjava What do you think about that ?

**Comment by amugofjava** [comment]
Longer term it would be better to force https across all connections, but the approach I would like to take is to store all urls as is, and force https upon usage. Looking at the PR, the urls are forced as https at the point they are written to Sembast and I don't think the situation where a user searches for a podcast and hits play or download without following the podcast is handled. I am also thinking about the extension code. It's personal preference, but the forceHttps method feels more like and extension to the url functions rather than String.

There is also an issue with the downloader when an https url redirects to an http one (the BBC seem to have several podcasts that do this) which I am also considering, but I'll raise another issue for this.

As this is a causing you issues I will merge #95 PR for now and come back to this.
